### PR TITLE
clean/simplify mcgroup

### PR DESCRIPTION
**Pull request by ghost**
- prefix module functions
- keep udp socket local
- simplify static common function

### CODE REVIEW

**Comment by pali** [comment]
I'm not a big fan of mixing upper-case and camel-case in one identifier. Also you should write commit messages more descriptive (see history for examples).

**Comment by ghost** [comment]
do you like "mcgroup_sendjoin"?

**Comment by pali** [comment]
Look, majority of igmpproxy code uses "camelCase" style with leading lowercase character.

**Comment by ghost** [comment]
Good, in this case a module prefix wont make sense i guess.
What about moving the function getMcGroupSock from rttable.c to mcgroup.c (intention to make it local/static)? I could make a separate pull request for that.

**Comment by pali** [comment]
So show code and then we can discuss about it.

**Comment by ghost** [comment]
this does not good in a direction i intended, i am not interested anymore to pull this changes

**Pull request closed without merging**
